replicaCount: 3

images:
  ipfs: "ipfs/go-ipfs:v0.12.2"
  ipfsCluster: "ipfs/ipfs-cluster:v1.0.0"

bootstrap:
  id: Qmd28KWdCmZUy4q26rLJ2d6jCW9FtcwtT6hRPxWHX8SHXt

service:
  type: NodePort
  ports:
    - name: swarm
      port: 4001
    - name: http
      port: 8080
    - name: http-proxy
      port: 9095

certificates:
  issuer:
    email: hello@lukso.network
  api:
    name: staging-api-ipfs-lukso-network
    domain: staging.api.ipfs.lukso.network
  gateway:
    name: staging-ipfs-lukso-network
    domain: staging.ipfs.lukso.network

ingress:
  enabled: true
  nameOfGlobalIP: global-staging-ipfs-lukso-network
