replicaCount: 3

images:
  ipfs: "ipfs/go-ipfs:v0.7.0"
  ipfsCluster: "ipfs/ipfs-cluster:v0.13.1"

bootstrap:
  id: Qmd7vkP2JFQDJmFm5zENEQGahsCdN8UeNWCxJq8Y3C8Ged

imagePullSecrets: []
podAnnotations: {}
podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

service:
  type: NodePort
  ports:
    - name: swarm
      port: 4001
    - name: http
      port: 8080
    - name: http-proxy
      port: 9095

certificates:
  gateway:
    name: ipfs-lukso-network
    domain: ipfs.lukso.network

ingress:
  enabled: true
  nameOfGlobalIP: ipfs-lukso-network
resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
