replicaCount: 3

images:
  ipfs: "ipfs/go-ipfs:v0.7.0"
  ipfsCluster: "ipfs/ipfs-cluster:v0.13.1"

bootstrap:
  id: Qmd7vkP2JFQDJmFm5zENEQGahsCdN8UeNWCxJq8Y3C8Ged

service:
  type: NodePort
  ports:
    - name: swarm
      port: 4001
    - name: http
      port: 8080
    - name: http-proxy
      port: 9095

certificates:
  issuer:
    email: hello@lukso.network
  api:
    name: api-ipfs-lukso-network
    domain: api.ipfs.lukso.network
  gateway:
    name: ipfs-lukso-network
    domain: ipfs.lukso.network

ingress:
  enabled: true
  nameOfGlobalIP: ipfs-lukso-network
