{{- if .Values.ingress.enabled -}}
{{- $fullName := include "ipfs-cluster.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    {{- include "ipfs-cluster.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ipfs-lukso-network
    networking.gke.io/managed-certificates: ipfs-lukso-network
spec:
  backend:
    serviceName: lukso-ipfs-cluster-gateway
    servicePort: 8080
  {{- end }}
