apiVersion: v1
kind: Service
metadata:
  name: ipfs-http-gateway
  labels:
    app: ipfs-cluster
spec:
  type: NodePort
  selector:
    app: ipfs-cluster
  ports:
    - name: swarm
      port: 4001
    - name: http
      port: 8080
    - name: proxy-http
      port: 9095
