apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs-cluster.fullname" . }}-gateway
  labels:
    {{- include "ipfs-cluster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app: {{ include "ipfs-cluster.fullname" . }}
