{{- if .Values.ingress.enabled -}}
{{- $fullName := include "ipfs-cluster.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress-gateway
  labels:
    {{- include "ipfs-cluster.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.nameOfGlobalIP }}
    networking.gke.io/managed-certificates: {{ .Values.certificates.gateway.name }}
spec:
  backend:
    serviceName: {{ $fullName }}-gateway
    servicePort: 8080
  rules:
    - host: {{ .Values.certificates.gateway.domain }}
      http:
        paths:
          - path: /ipfs
            backend:
              serviceName: {{ $fullName }}-gateway
              servicePort: 8080
  {{- end }}
